//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace devDesarrollo.models.Database
{

    public partial class categoria : XPLiteObject
    {
        int fidcategoria;
        [Key(true)]
        public int idcategoria
        {
            get { return fidcategoria; }
            set { SetPropertyValue<int>(nameof(idcategoria), ref fidcategoria, value); }
        }
        string fnombre;
        [Size(60)]
        public string nombre
        {
            get { return fnombre; }
            set { SetPropertyValue<string>(nameof(nombre), ref fnombre, value); }
        }
        string fdescripcion;
        [Size(80)]
        public string descripcion
        {
            get { return fdescripcion; }
            set { SetPropertyValue<string>(nameof(descripcion), ref fdescripcion, value); }
        }
    }

}
